# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodBody' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya',       '~> 13.0.1'
  pod 'ObjectMapper', '~> 3.5.0'
  pod 'IQKeyboardManagerSwift', '~> 6.4.0'
  pod 'Kingfisher', '~> 5.6.0'
  pod 'GoogleSignIn'
	pod 'FBSDKLoginKit'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  #firebase.
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'MBProgressHUD'
  pod 'Charts'
	pod 'FSCalendar', '~> 2.8.0'
  pod 'INSPhotoGallery', '1.2.8'
	
  target 'FoodBodyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodBodyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
